try{
    console.log("hllo");
    console.log(a);
    console.log(" ending try")

} catch(err){
    console.log("handled",err);
} finally{
    console.log("finally");

}
console.log("end");